//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Controls/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""CueControl"",
            ""id"": ""80588ed5-19ea-48c3-a073-4433b1b5ef81"",
            ""actions"": [
                {
                    ""name"": ""Horizontal"",
                    ""type"": ""Value"",
                    ""id"": ""83335f1b-6d33-476f-b147-a203ceb3d9e7"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Vertical"",
                    ""type"": ""Value"",
                    ""id"": ""73c231cf-8288-4bbb-ad67-dc673a554164"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Strength"",
                    ""type"": ""Value"",
                    ""id"": ""47c7d216-32be-4f44-982f-45156cbb041a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Value"",
                    ""id"": ""51aaac26-68f5-4359-8141-d23e55b12fdb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Value"",
                    ""id"": ""98c42a1a-fe23-4063-b5b3-7f466e390e61"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ea38b783-9340-4b5b-b79c-6da7952f7026"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""SteeringWheel"",
                    ""action"": ""Strength"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d56792aa-e1c3-40d7-863f-d503d2fb7944"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/stick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""SteeringWheel"",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be669c97-4dbe-4ae4-8396-e25a47b490de"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29e55307-1310-4913-b187-69074864038d"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/stick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ddf5f2c-8767-4c16-8755-a1cb6639b956"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""SteeringWheel"",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""SteeringWheel"",
            ""bindingGroup"": ""SteeringWheel"",
            ""devices"": [
                {
                    ""devicePath"": ""<HID::Logitech G29 Driving Force Racing Wheel>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // CueControl
        m_CueControl = asset.FindActionMap("CueControl", throwIfNotFound: true);
        m_CueControl_Horizontal = m_CueControl.FindAction("Horizontal", throwIfNotFound: true);
        m_CueControl_Vertical = m_CueControl.FindAction("Vertical", throwIfNotFound: true);
        m_CueControl_Strength = m_CueControl.FindAction("Strength", throwIfNotFound: true);
        m_CueControl_Up = m_CueControl.FindAction("Up", throwIfNotFound: true);
        m_CueControl_Down = m_CueControl.FindAction("Down", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CueControl
    private readonly InputActionMap m_CueControl;
    private List<ICueControlActions> m_CueControlActionsCallbackInterfaces = new List<ICueControlActions>();
    private readonly InputAction m_CueControl_Horizontal;
    private readonly InputAction m_CueControl_Vertical;
    private readonly InputAction m_CueControl_Strength;
    private readonly InputAction m_CueControl_Up;
    private readonly InputAction m_CueControl_Down;
    public struct CueControlActions
    {
        private @InputActions m_Wrapper;
        public CueControlActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Horizontal => m_Wrapper.m_CueControl_Horizontal;
        public InputAction @Vertical => m_Wrapper.m_CueControl_Vertical;
        public InputAction @Strength => m_Wrapper.m_CueControl_Strength;
        public InputAction @Up => m_Wrapper.m_CueControl_Up;
        public InputAction @Down => m_Wrapper.m_CueControl_Down;
        public InputActionMap Get() { return m_Wrapper.m_CueControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CueControlActions set) { return set.Get(); }
        public void AddCallbacks(ICueControlActions instance)
        {
            if (instance == null || m_Wrapper.m_CueControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CueControlActionsCallbackInterfaces.Add(instance);
            @Horizontal.started += instance.OnHorizontal;
            @Horizontal.performed += instance.OnHorizontal;
            @Horizontal.canceled += instance.OnHorizontal;
            @Vertical.started += instance.OnVertical;
            @Vertical.performed += instance.OnVertical;
            @Vertical.canceled += instance.OnVertical;
            @Strength.started += instance.OnStrength;
            @Strength.performed += instance.OnStrength;
            @Strength.canceled += instance.OnStrength;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
        }

        private void UnregisterCallbacks(ICueControlActions instance)
        {
            @Horizontal.started -= instance.OnHorizontal;
            @Horizontal.performed -= instance.OnHorizontal;
            @Horizontal.canceled -= instance.OnHorizontal;
            @Vertical.started -= instance.OnVertical;
            @Vertical.performed -= instance.OnVertical;
            @Vertical.canceled -= instance.OnVertical;
            @Strength.started -= instance.OnStrength;
            @Strength.performed -= instance.OnStrength;
            @Strength.canceled -= instance.OnStrength;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
        }

        public void RemoveCallbacks(ICueControlActions instance)
        {
            if (m_Wrapper.m_CueControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICueControlActions instance)
        {
            foreach (var item in m_Wrapper.m_CueControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CueControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CueControlActions @CueControl => new CueControlActions(this);
    private int m_SteeringWheelSchemeIndex = -1;
    public InputControlScheme SteeringWheelScheme
    {
        get
        {
            if (m_SteeringWheelSchemeIndex == -1) m_SteeringWheelSchemeIndex = asset.FindControlSchemeIndex("SteeringWheel");
            return asset.controlSchemes[m_SteeringWheelSchemeIndex];
        }
    }
    public interface ICueControlActions
    {
        void OnHorizontal(InputAction.CallbackContext context);
        void OnVertical(InputAction.CallbackContext context);
        void OnStrength(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
    }
}
